### ISSUE TITLE
ChartLabels not working on RN 0.64 due to worklet is not a function?

### ISSUE THREAD

**Issue by 18601673727** [rainbow-me/react-native-animated-charts#27]
https://github.com/software-mansion/react-native-reanimated/discussions/2004

**Comment by nikitph** [comment]
any solution you figured out @18601673727

**Comment by 18601673727** [comment]
@nikitph Downgrade react-native to 0.63.0 resolves
